### ISSUE TITLE
What is a banary?

### ISSUE THREAD

**Issue by johnblommers** [0x61nas/lqth#3]
I'm relatively new to Rust.

You refer to a banary.

Izzat a typo and you mean  binary or am I missing something?

Not a huge issue of  course. Thanks for sharing `lqth`.

**Comment by 0x61nas** [comment]
> you mean binary or am I missing something?

yep, I meant this

> Not a huge issue of course. 

On the contrary, every small improvement matters

> Thanks for sharing lqth.

I am delighted that you enjoy it 💙
